[build]
  base = "client"
  command = "npm run build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"

# Optional redirects if using React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
